# config.py

API_KEY = 'ONFWd14YybRFp143Dsl6DKxTKBp5niOvvE/3uiDgCoYn1Cwk/Um+dsIa'
API_SECRET = 'HB4j9wWxUgqe8gM2OXPYcwUkcq2kh9SDBLk7OacIRNx4UZvWdvbXdAlEV1bIHE6AWO0ONOCWQmqpl4RpFlbLOg=='

TRADING_PAIRS = ['BTC/USD', 'ETH/USD', 'ADA/USD', 'DOT/USD']
TRADE_VOLUME = 0.001

# Parámetros RSI
RSI_PERIOD = 14
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70