import os

API_KEY = os.getenv("API_KEY")
API_SECRET = os.getenv("API_SECRET")

TRADING_PAIRS = ['BTC/USD', 'ETH/USD', 'ADA/USD', 'DOT/USD']
TRADE_VOLUME = 0.001

RSI_PERIOD = 14
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70